# The configuration parameters below are used for HDAAGT-SinD model training and evaluation.

# General startup parameters
model_name: "HDAAGT-SinD"
sind_city: 'Changchun'
verbal: false # If true, it will print the configs parameters
sos: [1020,1020,0,0,0,0,0,0,0,0,0,0, 4, 4] # This is the start of the sequence for categorical variables
eos: [1022,1022,1,1,1,1,1,1,1,1,1,1, 5, 5] # This is the end of the sequence for categorical variables
detection_path: 'data/Changchun/'
lightpath: 'data/Changchun/Traffic_Lights.csv'
ZoneBoxes_path: 'configs/Boxes.pth'
generate_data: true #  Add class by loading the CSV file
Load_Model: false # It's for creating model from scratch
Load_Model_Path: 'Processed/Bestmodel.pth' # The path of the model to be loaded
Train: true # It's for training the model with the prepared data
Test: true # It's for testing the model with the prepared data
Test_during_training: true # It's for testing the model during training


# Model Architecture parameters
hidden_size: 128
num_heads: 4
Nusers: 32 # This is the number of users in the dataset for Graph Attention
Nnodes: 32 # This should be the same as Nusers
Num_linear_inputs: 17
concat: False
dropout: 0.2
output_dict_size: 1024


# Dataset parameters
# Header: ['BBX','BBY','VX', 'VY' , 'Yaw', 'AX', 'AY', 'ALon', 'ALat', 'VLon', 'VLat', 'Heading', 'LightX', 'LightY']
Columns_to_keep: [0,1,2,3,4,5,6,7,8,9,10,11,12,13] #['Zone','BBx', 'BBy','Tr1', 'Tr2', 'Tr3', 'Tr4']
xy_indx: [0,1] # the index of x and y  of the Columns_to_Keep used for speed calculation function
Traffic_indx: [12,13] # the index of the traffic light of the Columns_to_Keep used for speed calculation function
trf_embedding_dict_size: [6,6] # size of the embedding dictionary for ['Zone','BBx', 'BBy','Tr1', 'Tr2', 'Tr3', 'Tr4']
trf_embedding_dim: [16, 16] # size of the model dimension for ['Zone','BBx', 'BBy','Tr1', 'Tr2', 'Tr3', 'Tr4']
pos_embedding_dict_size: [1024, 1024]
pos_embedding_dim: [128, 128]


NZones: 10
NTrfL: 4
sl: 12 # sequence length
future: 12 # future prediction horizon
sw: 12 # sliding window for preparation of the dataset 
Centre: [512,512] # The centre of the image
dwn_smple: 2 # we can downsample the sequence length or future prediction by this factor
noise_multiply: 10 
noise_amp: 4 # pixels
noise_probability: 0.6 # probability of the noise



# Training parameters
learning_rate: !!float 4e-04
schd_stepzise: 15
gamma: 0.15
epochs: 45
patience_limit: 5
clip: 0.25
batch_size: 128